title: Portal Layanan Pendidikan Cabang Dinas Dikpora Wilayah IV
email: zainul@example.com
description: Website resmi Cabang Dinas Pendidikan, Pemuda, dan Olahraga Wilayah IV
baseurl: "" # biarkan kosong jika ini adalah repositori utama (username.github.io)
url: "https://cabdindikpora-wilayahiv.github.io/"
